import { Response, Request } from 'express';
import { PrismaClient } from '@prisma/client';

// Initialize Express app and Prisma client
const express = require('express');
const app = express(); // <--- Creates the application instance
const prisma = new PrismaClient();

/**
 * @summary This is the main POST call for the feedback form. It will create a new submission in the database with the form and email provided in the request body. The ID will be auto-generated by the database, so we do not need to include it in the request body or destructure it here.
 */ 
app.post('/users', async (req: Request, res: Response) => {
  const { form, email } = req.body; // Do not destructure "id" here

  try {
    const newSubmission = await prisma.feedbackSubmission.create({
      data: {
        form,
        email,
      },
    });

    // The returned "newUser" object will include the auto-generated ID
    res.status(201).json(newSubmission); 
  } catch (error) {
    res.status(500).json({ error: 'Failed to create submission' });
  }
});

/**
 * @summary Add report is the main adding report page and from there
 *          we can add other reports ie - addSurfaceCoverageReport 
 */ 
const addReport = (req: Request, res: Response) => {
  res.status(200).send('Add report is working');
};


/**
 * @summary     Test is just as it says a test page. For now it is just
 *              for now it is just a blank page and the logs will only 
 *              show up in the compiler. It is just testing to see if CRUD
 *              commands are working with the database
 * @param req   a request being sent to this api endpoint
 * @param res   the response being sent by this api endpoint
 */

const test = async (req: Request, res: Response)=> {
  // add test
  const testAdd = await prisma.user.create({
    data: {
      email: 'test@test.com',
      name: 'test'
    }
  });

  console.log(testAdd);

  // find test
  const testFind = await prisma.user.findMany({
    where: {
      email: 'test@test.com',
      name: 'test'
    }
  });

  console.log(testFind);

  // delete test
  const testDelete = await prisma.user.delete({
    where: {
      email: 'test@test.com',
      name: 'test'
    }
  });

  console.log(testDelete);

  res.status(200).send('this is a test');
}

export {addReport, test};