apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone-2026-metabase
spec:
  selector:
    matchLabels:
      app: metabase
  replicas: 1
  template:
    metadata:
      labels:
        app: metabase
    spec:
      initContainers:
        - name: init-metabase-dirs
          image: docker.io/library/busybox:1.36.1
          command: ["sh", "-c", "mkdir -p /tmp /plugins /metabase-data"]
          resources:
            requests:
              cpu: "10m"
              memory: "20Mi"
            limits:
              cpu: "100m"
              memory: "50Mi"
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 1011540000
            runAsGroup: 1011540000
            readOnlyRootFilesystem: true
            seccompProfile:
              type: RuntimeDefault
            capabilities:
              drop:
                - ALL
          volumeMounts:
            - name: tmp-dir
              mountPath: /tmp
            - name: plugins-dir
              mountPath: /plugins
            - name: metabase-data-dir
              mountPath: /metabase-data
      containers:
        - name: metabase
          image: docker.io/metabase/metabase:v0.50.15
          # command:
          #   [
          #     "java",
          #     "--add-opens",
          #     "java.base/java.nio=ALL-UNNAMED",
          #     "-Djava.io.tmpdir=/tmp",
          #     "-jar",
          #     "/app/metabase.jar",
          #     "migrate",
          #     "down",
          #   ]
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 1011540000
            runAsGroup: 1011540000
            readOnlyRootFilesystem: true
            seccompProfile:
              type: RuntimeDefault
            capabilities:
              drop:
                - ALL
          ports:
            - containerPort: 3000
              protocol: TCP
          env:
            - name: MB_PLUGINS_DIR
              value: "/plugins"
            - name: JAVA_OPTS
              value: "-Xms512m -Xmx1024m -Djava.io.tmpdir=/tmp"
            - name: MB_DB_TYPE
              value: "postgres"
            - name: MB_DB_HOST
              value: "capstone-db-service"
            - name: MB_DB_PORT
              value: "5432"
            - name: MB_DB_DBNAME
              value: "metabase_metadata"
            - name: MB_DB_USER
              value: "postgres"
            - name: MB_DB_PASS
              value: "default"
            - name: MB_ENCRYPTION_SECRET_KEY
              value: "Ij9BIxilMImF4RzMs3Z7+RKqAj2uXdsp2m8x6FRgkwA="
            - name: MB_DB_AUTOMATIC_CREATION
              value: "true"
          resources:
            requests:
              memory: "512Mi"
              cpu: "50m"
            limits:
              memory: "1500Mi"
              cpu: "1000m"
          volumeMounts:
            - name: tmp-dir
              mountPath: /tmp
            - name: plugins-dir
              mountPath: /plugins
            - name: metabase-data-dir
              mountPath: /metabase-data
      volumes:
        - name: tmp-dir
          emptyDir: {}
        - name: plugins-dir
          emptyDir: {}
        - name: metabase-data-dir
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: metabase-svc
spec:
  type: ClusterIP
  selector:
    app: metabase
  ports:
    - name: http
      port: 8080
      targetPort: 3000
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: metabase-route
spec:
  to:
    kind: Service
    name: metabase-svc
  port:
    targetPort: http
  tls:
    termination: edge
